#!/bin/bash

BUILDPATH=${PWD}/build
PREFIX=/
export MACOSX_DEPLOYMENT_TARGET="10.13"
RESOURCES=/Applications/Utilities/OpenSCTokenApp.app/Contents/PlugIns/OpenSCToken.appex/Contents/Resources

xcode_ver=$(xcodebuild -version | sed -En 's/Xcode[[:space:]](.*)/\1/p')
base_ver="12.2"
if [ $(echo -e $base_ver"\n"$xcode_ver | sort -V | head -1) == "$base_ver" ]; then
	export BUILD_ARM="true"
fi

set -ex

if [ -z "$OPENSSL_CFLAGS" -a -z "$OPENSSL_LIBS" ] ; then
	if ! test -e $BUILDPATH/openssl/$PREFIX/lib/pkgconfig; then
		# Build OpenSSL manually, because Apple's binaries are deprecated
		if ! test -e openssl; then
			git clone --depth=1 https://github.com/openssl/openssl.git -b openssl-3.0
		fi
		cd openssl
		sed -ie 's!my @disablables = (!my @disablables = (\n    "apps",!' Configure
		./Configure darwin64-x86_64 no-shared no-apps no-dso no-engine --prefix=$PREFIX enable-ec_nistp_64_gcc_128
		make clean
		make -j 4
		make DESTDIR=$BUILDPATH/openssl_bin install_sw
		make clean
		./Configure darwin64-arm64 no-shared no-apps no-dso no-engine --prefix=$PREFIX enable-ec_nistp_64_gcc_128
		make -j 4
		make DESTDIR=$BUILDPATH/openssl_arm64 install_sw
		lipo -create $BUILDPATH/openssl_arm64/$PREFIX/lib/libcrypto.a $BUILDPATH/openssl_bin/$PREFIX/lib/libcrypto.a -output libcrypto.a
		lipo -create $BUILDPATH/openssl_arm64/$PREFIX/lib/libssl.a $BUILDPATH/openssl_bin/$PREFIX/lib/libssl.a -output libssl.a
		mv libcrypto.a $BUILDPATH/openssl_bin/$PREFIX/lib/libcrypto.a
		mv libssl.a $BUILDPATH/openssl_bin/$PREFIX/lib/libssl.a
		cd ..
	fi
	export OPENSSL_CFLAGS="`env PKG_CONFIG_PATH=$BUILDPATH/openssl_bin/$PREFIX/lib/pkgconfig PKG_CONFIG_SYSROOT_DIR=$BUILDPATH/openssl_bin pkg-config --static --cflags libcrypto`"
	export OPENSSL_LIBS="`  env PKG_CONFIG_PATH=$BUILDPATH/openssl_bin/$PREFIX/lib/pkgconfig PKG_CONFIG_SYSROOT_DIR=$BUILDPATH/openssl_bin pkg-config --static --libs   libcrypto`"
	export CRYPTO_CFLAGS="$OPENSSL_CFLAGS"
	export CRYPTO_LIBS="$OPENSSL_LIBS"
fi

export CFLAGS="$CFLAGS -arch x86_64 -arch arm64"
export LDFLAGS="$LDFLAGS -arch x86_64 -arch arm64"
export OBJCFLAGS=$CFLAGS

if ! test -e $BUILDPATH/openpace_bin/$PREFIX/lib/pkgconfig; then
	if ! test -e openpace; then
		git clone --depth=1 https://github.com/frankmorgner/openpace.git -b 1.1.3
	fi
	cd openpace
	autoreconf -vis
	./configure --disable-shared --prefix=$PREFIX HELP2MAN=/usr/bin/true
	touch src/cvc-create.1 src/cvc-print.1
	make DESTDIR=$BUILDPATH/openpace_bin install
	cd ..
fi
export OPENPACE_CFLAGS="`env PKG_CONFIG_PATH=$BUILDPATH/openssl_bin/$PREFIX/lib/pkgconfig:$BUILDPATH/openpace_bin/$PREFIX/lib/pkgconfig PKG_CONFIG_SYSROOT_DIR=$BUILDPATH/openpace_bin pkg-config --static --cflags libeac` $OPENSSL_CFLAGS"
export OPENPACE_LIBS="`  env PKG_CONFIG_PATH=$BUILDPATH/openssl_bin/$PREFIX/lib/pkgconfig:$BUILDPATH/openpace_bin/$PREFIX/lib/pkgconfig PKG_CONFIG_SYSROOT_DIR=$BUILDPATH/openpace_bin pkg-config --static --libs   libeac` $OPENSSL_LIBS"

if ! test -e OpenSC; then
	git clone --depth=1 https://github.com/OpenSC/OpenSC.git
fi
cd OpenSC
if ! test -e configure; then
	autoreconf -vis
fi
./configure --disable-shared --prefix=$PREFIX --sysconfdir=$RESOURCES --disable-pcsc  --enable-cryptotokenkit
make
cd ..
